Shopify/sorbet

- main/pipeline/pipeline.cc
- test/prism_regression/multi_statements.parse-tree.exp
- test/prism_regression/multi_statements.rb
Sorbet constructs slightly different ASTs depending on whether a program contains one statement or more than one statements. Correctly parsing programs with more than one statement will make it easier to benchmark this project.
Sorbet constructs slightly different ASTs depending on whether a program contains one statement or more than one statements. Correctly parsing programs with more than one statement will make it easier to benchmark this project.
Added automated tests for parsing a multi-statement program.
> Implement prism -> sorbet conversion for multi-statement programs

- parser/prism/Translator.cc
- test/prism_regression/constants.parse-tree.exp
- test/prism_regression/constants.rb
Closes #73, Closes #78.
Needed for #62, to support `class` blocks with a superclass
> Implement Prism -> Sorbet translation for constant references

- tools/scripts/build_compilation_db.sh
Temporary workaround for this limitation:
https://github.com/Shopify/sorbet/blob/15372d7937c0215181122b82b44e54ac86c53492/third_party/prism.BUILD#L17-L23
Which lets you manually define the `RUBY_VERISON`:
```sh
./tools/scripts/build_compilation_db.sh --define RUBY_PATH='/opt/rubies/3.3.4/'
```
> Forward `build_compilation_db.sh` args to its Bazel build command

- parser/prism/Translator.cc
Currently, an unimplemented node type just returns a `nullptr` and causes a downstream crash.
This PR replaces it with a string literal, which contains the name of the type of node that was reached. This is useful for quickly knowing "what do I need to implement next?" just from looking at the test output.
E.g. given
```rb
def foo
while true; end
end
```
I get this failure:
```diff
test/helpers/expectations.cc:209: ERROR: Mismatch on: test/prism_regression/while.parse-tree.exp
If these changes are expected, run this script and commit the results:
tools/scripts/update_testdata_exp.sh
@@ -1,2 +1,8 @@
+DefMethod {
+  name = <U foo>
+  args = NULL
+  body = String {
+    val = <U Unimplemented node type PM_WHILE_NODE (#148).>
+  }
+}
```
Making it clear that I need to implement `case …
> Use a string literal as the default fallback

- parser/prism/Translator.cc
- test/prism_regression/super.parse-tree.exp
- test/prism_regression/super.rb
Closes #93
Closes #172
Depends on the `translateArguments()` helper from #197.
> Implement Prism -> Sorbet translation for `super` calls

- parser/prism/Translator.cc
- test/prism_regression/begin.parse-tree.exp
- test/prism_regression/begin.rb
Closes #47 
Translates `PM_BEGIN_NODE`s from Prism to Sorbet.
These represent begin blocks, e.g.
```ruby
begin
rescue
end
```
Note that I haven't implemented support for `rescue` (#160), `ensure` (#86) or `else` because they're not needed for parsing the RBI gem.
> Implement translation for `PM_BEGIN_NODE`

- parser/prism/Translator.cc
- test/prism_regression/rational.parse-tree.exp
- test/prism_regression/rational.rb
- third_party/externals.bzl
Use the latest version of Prism!
> Bump Prism to v0.30.0

- parser/prism/Translator.cc
- parser/prism/Translator.h
Another stab at #193. We don't really need a general `map` function, because the transformation is always the same (`[this](auto &node) { return translate(node); }`).
This PR adds 3 related functions, which serve to produce a `NodeVec` from multiple Prism nodes.
> Add `translateMulti` helper to clean up some loops

- parser/prism/Translator.cc
- test/prism_regression/assoc_splat.parse-tree.exp
- test/prism_regression/assoc_splat.rb
> Implement translation for `PM_ASSOC_SPLAT_NODE`

- parser/prism/Translator.cc
- test/prism_regression/assign_to_instance_variable.parse-tree.exp
- test/prism_regression/assign_to_instance_variable.rb
- test/prism_regression/assign_to_local_variable.parse-tree.exp
- test/prism_regression/assign_to_local_variable.rb
Closes #111
Closes #112 
Closes #113 
Closes #126 
Closes #127 
Closes #128
> Implement Sorbet -> Prism translations for op assigns for local and instance variables

- parser/prism/Translator.cc
- test/prism_regression/assign_to_index.parse-tree.exp
- test/prism_regression/assign_to_index.rb
Closes #107
Closes #108 
Closes #109
> Implement Prism -> Sorbet translation for index assign nodes

- parser/prism/Translator.cc
- parser/prism/Translator.h
- test/prism_regression/def_all_params.parse-tree.exp
- test/prism_regression/def_all_params.rb
- test/prism_regression/def_block_param.parse-tree.exp
- test/prism_regression/def_block_param.rb
- test/prism_regression/def_kw_rest_params.parse-tree.exp
- test/prism_regression/def_kw_rest_params.rb
- test/prism_regression/def_rest_params.parse-tree.exp
- test/prism_regression/def_rest_params.rb
Further additions to #51, #124, #161.
> Implement missed translations for anonymous `*`, `**` and `&` params

- ast/desugar/Desugar.cc
- parser/prism/Translator.cc
- test/prism_regression/array.parse-tree.exp
- test/prism_regression/array.rb
- test/prism_regression/call_kw_rest_params.parse-tree.exp
- test/prism_regression/call_kw_rest_params.rb
- test/prism_regression/call_rest_params.parse-tree.exp
- test/prism_regression/call_rest_params.rb
- test/prism_regression/hash.parse-tree.exp
- test/prism_regression/hash.rb
Builds on top of #42 and #225 to add support for anonymous splats.
> Implement Prism -> Sorbet translation for anonymous Array and Hash splats

- parser/prism/Parser.cc
We assumed that the `pm_string_t` objects being passed as arguments to this method would need to be freed from memory, but because they are all referenced by nodes in the Prism AST, they will be freed once the tree is destroyed.
Automated tests should continue to pass.
> Remove the exception from the `extractString` method

- parser/prism/Translator.cc
- test/prism_regression/case.parse-tree.exp
- test/prism_regression/case.rb
- test/prism_regression/case_match.parse-tree.exp
- test/prism_regression/case_match.rb
This PR implements pattern matching in `case` statements.
* Handles exact matches like `in 1`
* Handles all kinds of Array patterns like `in [1, 2]`, but doesn't implement qualifying them with a constant (e.g. `Array[1, 2]`)
* Handles "find" patterns, like `[*, 1, 2, *]`
Doesn't implement:
* anything related to Hash patterns
* variable binding (`in [1, x]`)
* variable pinning (`in ^existing_value`)
* guard clauses (`in Integer if predicate`)
* probably other stuff. there's a lot of pattern matching syntax :)
Closes #43
Closes #60
Closes #88
Closes #106
> Implement Prism -> Sorbet translation for basic pattern matching

- parser/prism/Translator.cc
- test/prism_regression/array.parse-tree.exp
- test/prism_regression/call_rest_params.parse-tree.exp
- test/prism_regression/def_all_params.parse-tree.exp
- test/prism_regression/def_rest_params.parse-tree.exp
I noticed that `prism` branch's CI is failing around rest parameters after merging the latest `sorbet` master. And when I regenerated the parse trees, I can indeed see them being outdated. So in this PR I updated the parse trees and the related translation logic, as well as adding a task to generate prism parse trees.
I do have a question though: why were the tests failing if both parse trees and translation were outdated? Do we also compare the committed parse trees with Sorbet's current parse trees in tests too?
> Update rest parameter translation

- .github/workflows/ci.yml
Closes https://github.com/Shopify/team-ruby-dx/issues/1187
This PR adds [setup-bazel](https://github.com/bazel-contrib/setup-bazel) to our CI workflow, which will cache Bazel between runs, significantly shortening the build time for our automated tests.
Our tests run and pass a lot faster now! They used to take about 20 minutes, and [the build on this branch took 2.5](https://github.com/Shopify/sorbet/actions/runs/11223676474/job/31198802255?pr=262) :)
> Use `setup-bazel` to cache Bazel in CI

- .vscode/tasks.json
- parser/prism/Translator.cc
- test/prism_regression/xstring.parse-tree.exp
- test/prism_regression/xstring.rb
Closes https://github.com/Shopify/sorbet/issues/121
In the second commit, I merged single/all location tests into regression tests as I feel it's more convenient to run them together.
Example:
```
INFO: Elapsed time: 10.133s, Critical Path: 10.00s
INFO: 11 processes: 12 local.
INFO: Build completed, 2 tests FAILED, 11 total actions
//test:prism_regression_xstring_location_test                            FAILED in 2.9s
/private/var/tmp/_bazel_hung-wulo/4a66351d4da81785705c4ebcb28c4103/execroot/com_stripe_ruby_typer/bazel-out/darwin_arm64-dbg/testlogs/test/prism_regression_xstring_location_test/test.log
//test:test_PosTests/prism_regression/xstring                            FAILED in 4.0s
/private/var/tmp/_bazel_hung-wulo/4a66351d4da81785705c4ebcb28c4103/execroot/com_stripe_ruby_typer/bazel …
```
> Support translating interpolated xstrings

- parser/prism/Translator.cc
- parser/prism/Translator.h
After #269, `translateSimpleKeyword()` no longer needs its `PrismNode` template parameter, because it no longer needs to be able to cast the `untypedNode` to a concrete node type.
This PR demonstrates what the code would like without that first template parameter.
IMHO, I think having the Prism type listed is kind of nice from a self-documenting-code perspective, even if it is technically redundant. I'm posting PR to collect feedback, @egiurleo @st0012.
> Remove template param from `translateSimpleKeyword()`

- .github/workflows/ci.yml
Getting all the test output was not particularly useful and created a lot of noise.
> Pass `--test_output=errors` flag to CI

- parser/prism/Translator.cc
- parser/prism/Translator.h
This is necessary because some Prism nodes get translated differently depending on whether they're part of "regular" syntax, or pattern-matching syntax.
E.g. `PM_LOCAL_VARIABLE_TARGET_NODE` normally translates to `parser::LVarLhs`, but `parser::MatchVar` in the context of a pattern.
E.g. replace `patternTranslate(node)` calls with something like:
```c++
auto isInPatternMatch = true;
Translator::Context ctx{isInPatternMatch};
return translate(ctx, node);
```
* Pro: doesn't require splitting the one big `switch`
* Con: lots of `case`s will now be wrapped in big `if` statements to do one thing or another, based on the context.
* Pro: At least this makes it see all the possible translations for a given node.
* Con: extra param to all recursive calls.
E.g.
```c++
auto oldState = …
```
> Move pattern-matching code into a new set of functions

- parser/prism/Translator.cc
- test/prism_regression/case_match_variable_binding.parse-tree.exp
- test/prism_regression/case_match_variable_binding.rb
Closes #130
Related #43, #44, #101, #130
Stacked on top of #274
This PR implements the ability to bind variables inside patterns, including nesting bindings inside Array and Hash patterns.
> Implement Prism -> Sorbet translation for variable binding in patterns

- parser/prism/Translator.cc
- test/prism_regression/case_match_variable_binding.parse-tree.exp
- test/prism_regression/case_match_variable_binding.rb
Closes #150
Closes #151
Builds on top of #275
> Implement Prism -> Sorbet translation for pinning patterns

- parser/prism/Translator.cc
- test/prism_regression/call_block_param.parse-tree.exp
- test/prism_regression/call_block_param.rb
Closes #49
Block local variables are "readonly" (can't have assignment) and looks like it's purpose is to shield the variables inside the block from the outer scope?
```rb
bar = 1
foo do |x|
puts bar # 1
end
foo do |x; bar|
puts bar # nil
end
```
> Support translating block local variables

- parser/prism/Translator.cc
- parser/prism/Translator.h
- test/prism_regression/match_last_line.parse-tree.exp
- test/prism_regression/match_last_line.rb
Closes #132
Handles syntax like this:
```ruby
if /wat/
end
```
which is _not_ just testing the truthiness of a regex literal. It's implicitly testing if the last read line (`$_`) matches the pattern.
Sorbet doesn't support it today ([Sorbet.run](https://sorbet.run/#if%20%2Fx%2F%0Aend)), but we still need to translate it, to get that diagnostic.
> Implement Prism -> Sorbet translation for “last line matches”

- .github/workflows/ci.yml
- .vscode/tasks.json
- WORKSPACE
- third_party/prism.BUILD
- third_party/ruby_root.bzl
Related to Shopify/team-ruby-dx#1234
Up to this point, in order to build Prism, we've needed to manually pass the path to the correct RUBY version to the build process because Bazel does not take the user's environment into account and will just usethe system's default Ruby version (which is often very old).
This is an okay workaround, but it will not be acceptable once we try to upstream these changes.
There are a few potential paths forward:
While this seems like the most "Bazel-y" way to do things, this means we/the Sorbet team at Stripe would have to maintain a whole Ruby build pipeline just to build Prism, which partially defeats the purpose of adopting Prism in order to reduce the cost of maintaining the parser.
I still think we should explore this route, but it'll take some time …
> RFC: Automatically get `RUBY_ROOT` from user environment

- parser/prism/Translator.cc
- test/prism_regression/back_reference_read.parse-tree.exp
- test/prism_regression/back_reference_read.rb
> Implement Prism -> Sorbet translation for `PM_BACK_REFERENCE_READ_NODE`

- parser/prism/Translator.cc
- test/prism_regression/def.parse-tree.exp
- test/prism_regression/def.rb
- test/prism_regression/ensure.parse-tree.exp
- test/prism_regression/ensure.rb
- test/prism_regression/rescue.parse-tree.exp
- test/prism_regression/rescue.rb
If the method body is a `PM_BEGIN_NODE` instead of a `PM_STATEMENTS_NODE`, it means the method definition doesn't have an explicit begin block. If that's the case, we need to check if the body contains an ensure or rescue clause, and if so, we need to elevate that node to the top level of the method definition, without the `Kwbegin` node to match the behavior of Sorbet's legacy parser.
> Extract ensure/rescue clause from method body if no begin block is present

- parser/prism/BUILD
- parser/prism/Helpers.h
- parser/prism/Translator.cc
`reinterpret_cast` is a sharp blade, and we use it a lot. This is the first of several PRs that aims to tame our use of reinterpret casts, by wrapping them into helpers that add static and/or runtime checks to help ensure they're being used correctly.
This PR adds `up_cast`, which takes a pointer to any Prism node type, and casts it back to a `pm_node_t *`. This replaces usages of `reinterpret_cast<pm_node_t *>`, which is more dangerous because it could be given any type of pointer, not necessarily a Prism node.
One nice feature is that if the input type is _already_ `pm_node_t`, then this helper will raise a compiler error, telling you that you didn't need it.
```
In file included from parser/prism/Translator.cc:2:
parser/prism/Helpers.h:166:5: error: static assertion failed due to …
```
> Extract `up_cast` helper.

- parser/prism/Translator.cc
- test/prism_regression/case_match.parse-tree.exp
- test/prism_regression/case_match.rb
- test/prism_regression/if.parse-tree.exp
- test/prism_regression/if.rb
- test/prism_regression/unless.parse-tree.exp
- test/prism_regression/unless.rb
Closes #204
When investigating #204 I found that Parser's `IfGuard` and `UnlessGuard` are associated with these comments:
And I found that they're not handled by the current pattern translation yet. For example:
```rb
case bar
in x if x == 1
"in with if"
in a, b if b == 2
"in with 2 args and if"
in c, d; c if c == 3
"in with 2 args, semicolon, and if"
end
case baz
in x unless x == 1
"in with unless"
in a, b unless b == 2
"in with 2 args and unless"
in c, d; c unless c == 3
"in with 2 args, semicolon, and unless"
end
```
So this PR adds support for those cases.
> Translate conditionals in `in` statements

- parser/prism/Translator.cc
- test/prism_regression/pattern_matching_operators.parse-tree.exp
- test/prism_regression/pattern_matching_operators.rb
Closes #133, #134
Those nodes are `in` and `=>` operators used outside of case statements.
```rb
val in pattern
val => pattern
```
> Translate pattern matching operators

- .vscode/extensions.json
- .vscode/launch.json
- .vscode/tasks.json
This is based on @amomchilov's prior work in https://github.com/Shopify/sorbet/compare/prism...Shopify:sorbet:Alex/vscode-debugging
https://github.com/user-attachments/assets/28643ec5-494b-4922-b9b0-66c6786c0333
I'll also add this to #279 so we remove these stuff before upstreaming.
> Support debugging individual Prism tests in VS Code

- parser/prism/Helpers.h
In our debug builds, our `down_cast` helper verifies that the pointed-to node actually is the kind of node we're trying to cast it to. Doing this requires us to check the `type` field, which will fail if given `nullptr`.
We modify the `ENFORCE` check to either:
1. Allow `nullptr`
2. otherwise nullptr, check for the correct type.
This is safe because of the short-circuiting behaviour of `||`.
Automated tests continue to pass
> Fix crash when attempting to dow-cast `nullptr` in debug builds

- .vscode/tasks.json
- main/pipeline/pipeline.cc
- parser/prism/Translator.cc
- parser/prism/Translator.h
- test/prism_location_test.bzl
- test/prism_regression/error_recovery/assign.parse-tree.exp
- test/prism_regression/error_recovery/assign.rb
First step to #309
I'd like to approach this task with these steps:
1. Since node locations are important for autocorrection, we first make sure parse-trees still match in errored cases. So at this time we don't report errors at the same details & location as Sorbet does, as long as there are errors and they are captured in the fixtures, which we can used for comparison later.
2. Once we got all the parse-trees right, we compare all fixtures under `prism_regression/error_recovery/` with `testdata/parser/error_recovery/` and try to enrich/calibrate our error reporting.
- This doesn't include `error: Hint:` but only real syntax errors
4. Finally, we start working on `error: Hint`
With that in mind, in this PR:
1. To make it easier to compare with Sorbet's tests, I added `error_recovery` …
> Start reporting errors from the translator 

- .vscode/launch.json
- .vscode/tasks.json
It turns out that we only need `sourceMap`'s value to be set to the workspace folder with any arbitrary key. So not setting `BAZEL_EXEC_ROOT` is fine.
When reviewing #312, I [found](https://github.com/Shopify/sorbet/pull/312/files#r1821555693) that having bazel's execroot being the source map key is actually unnecessary. What's required seems to just be the value being the workspace folder. So in this PR I'm removing the task that sets `BAZEL_EXEC_ROOT` and updating `launch.json` entries.
> Remove unnecessary task to set `BAZEL_EXEC_ROOT`

- parser/prism/Translator.cc
- parser/prism/Translator.h
- test/prism_regression/assign_to_constant.parse-tree.exp
- test/prism_regression/assign_to_constant.rb
- test/prism_regression/rescue.parse-tree.exp
- test/prism_regression/rescue.rb
Related to #316 
Easiest to read each commit separately.
This PR addresses some issues with `PM_RESCUE_NODE`:
1. First, we were relying on the body of the begin node within the rescue to determine the location. It is entirely possible that the rescue will not have a body.
2. We were doing the dynamic constant assignment workaround for *all* the node types that passed through `translateConst`, rather than just the ones that actually handle constant assignment.
3. We weren't testing the dynamic constant assignment workaround with all the different types of constant assignment.
> Fix bugs in translation of `PM_RESCUE_NODE`

- main/pipeline/pipeline.cc
- parser/prism/Parser.cc
- parser/prism/Parser.h
- parser/prism/Translator.cc
- parser/prism/Translator.h
- test/prism_regression/error_recovery/assign.rb
Part of #309 
After #318, I found that we should pass Prism errors translator instead of just relying on `PM_MISSING_NODE` because:
- To generate `error: Hint: ...` like Sorbet's parser does, we need to have access to more context
- In some errored cases, the current translator still generates different parse-tree than Sorbet's parser. To solve this we need a translator-level context to update the translation in those cases
So in this PR, I start to feed Prism errors to the translator and report them when we hit a `PM_MISSING_NODE`. This prevents runtime(-ish?) errors like dynamic constant assignment error being reported proactively. We will revise this in later PRs when we understand better around error translation.
> Report Prism parse errors

- .vscode/tasks.json
- parser/prism/Parser.cc
- parser/prism/Parser.h
- parser/prism/Translator.cc
- test/prism_regression/error_recovery/assign.rb
- tools/scripts/inspect_parsing_errors.rb
1. Because neither Ruby LSP's `Show syntax tree` command nor websites like [Ruby Playground](https://ruby.github.io/play-ruby/) displays Prism's error messages, I added a new task to display a file's parse tree and Prism errors. This will make it easier to work with syntax-incorrect Ruby files.
2. [Keep Prism error id's type for easy comparison](https://github.com/Shopify/sorbet/commit/b4440c85e8c39a998fe13990f3e701618572d253) 
We currently don't use the converted value and keeping the `pm_diagnostic_id_t` type makes it easy to compare the value with `PM_ERR_*` constants directly.
3. [Stop surfacing Prism's EOF error](https://github.com/Shopify/sorbet/commit/ce141666804074b369b2f63670aae072081b6629) 
It usually appears when there's an unclosed statements/assignments, where the root error …
> Some improvements around error tolerance

- test/prism_location_test.sh
When I implemented the Prism location test runner, I accidentally switched the diff output so the expected parse tree showed up as the test output and vice versa.
For example, if I purposely make the `alias` location tests error by removing the symbol name, this is what the output looks like:
```
"type" : "Alias",
"from" : {
"type" : "Symbol",
-        "val" : ""
+        "val" : "new_method1"
},
```
This PR just fixes the test output, making it correct and easier for us to read.
> Fix output of Prism location test errors

- .github/workflows/ci.yml
- .vscode/tasks.json
- test/BUILD
- test/pipeline_test.bzl
Best read commit-by-commit.
So far in this project, we have been exclusively running new tests to ensure that we do not regress as we add more to our Prism -> Sorbet translation layer. We have not been running any of the existing Sorbet tests.
In order to gain more confidence in our work and upstream to Sorbet, it makes sense to start running more of the pre-existing Sorbet tests with the Prism parser.
My plan was to start with just the parser tests (many of which are currently failing), and once we're confident in those, add more and more of the Sorbet pipeline. Right now, I don't think it makes sense to run these tests in CI, but once more are passing, I think it would make sense.
This PR adds a Prism test corpus and some tasks for easily running it!
> Start running Sorbet corpus tests with Prism

- test/BUILD
- test/pipeline_test.bzl
Because pipeline_tests handles packager tests differently, we need to add Prism handling for them too. Otherwise, we'll get test conflict errors when `test_corpus_prism`'s pattern covers packager tests.
> Add Prism handling for packager tests too

- .vscode/launch.json
- test/pipeline_test_runner.cc
Closes #331
Some of the Sorbet corpus tests are failing with the error `enforced condition !nameTableFrozen has failed`, but the issue was actually that we were attempting to run part of the test with old Sorbet parser, rather than with Prism. I'm assuming this was attempting to create new entries in the name table when we didn't expect any more, which was causing the error.
The Sorbet test pipeline actually has multiple entry points for the parser -- there are two calls to the `index` method ([one here](https://github.com/Shopify/sorbet/blob/prism/test/pipeline_test_runner.cc#L434), [one here](https://github.com/Shopify/sorbet/blob/prism/test/pipeline_test_runner.cc#L441)) and then another pass where the pipeline re-parses some of the files …
> Fix test failures stemming from stemming from test pipeline 

- .vscode/launch.json
- .vscode/tasks.json
- parser/prism/Translator.cc
- test/prism_regression/literal_complex.parse-tree.exp
- test/prism_regression/literal_complex.rb
Unlike Integer or Float, Complex literals with prefix `-` or `+` should be translated to method calls on the Complex literal.
Closes #339 (that test would still fail due to error messages, but the trees match now)
The first commit splits the test name input into `prism_regression_test_name` and `prism_corpus_test_name`, so when we run one type of tests, the other type's previous input doesn't get erased.
> Properly handle complex literals with `+` or `-` prefix

- .github/workflows/ci.yml
- test/BUILD
This change has two motivations:
1. Start running the Prism corpus tests in CI to make sure we don't break anything
2. Explicitly document which tests we're skipping so we know what to return to once we're ready to handle error recovery
> Start running Prism Corpus tests in CI

- parser/prism/Translator.cc
- parser/prism/Translator.h
- test/BUILD
Closes #340 
We were not correctly maintaining the value of `uniqueCounter` when creating and then exiting a new translator instance. This was causing one of the desugar tests to fail because the parse tree was different between Prism and Sorbet, as the anonymous block params were being assigned different unique index numbers.
This PR also adds the desugar tests to our test corpus runs!
> Fix usage of unique counter in Prism -> Sorbet translation

- parser/prism/Translator.cc
- test/BUILD
Closes #347 
One desugar test was failing because we weren't correctly handling conditional sends in call operator write nodes.
When a call operator write (plus and/or operator writes) has a conditional send as the receiver, the left-hand-side node has to be a `CSend` rather than a `Send`.
We can now run the `testdata/desugar/csend` corpus test.
> Handle safe navigation/conditional send in call operator write nodes

- parser/prism/Translator.cc
- test/BUILD
- test/prism_regression/def_singleton.parse-tree.exp
- test/prism_regression/def_singleton.rb
Closes #349
Closes #352
Closes #353
The `desugar/defs_not_self` test revealed that we are not correctly handling method definitions with receivers.
> Translate Prism `PM_DEF_NODE` with receivers as `DefS` nodes in Sorbet

- parser/prism/Translator.cc
- test/BUILD
- test/prism_regression/call_block_param.parse-tree.exp
- test/prism_regression/call_block_param.rb
When the splat arg's expression is an `Arg`, we need to translate it to a `Restarg` instead of a `SplatLhs`.
Closes #357
> Fix splat arg translation

- test/BUILD
- test/helpers/position_assertions.cc
- test/helpers/position_assertions.h
Currently, corpus tests may fail with Prism for a few reasons:
1. The error checking fails with Prism. This is expected.
2. There are tree mismatches.
And sometimes, a test fail because of both 1 and 2.
This means that by skipping the test altogether, we are potentially skipping legitimately failing tests.
This commit updates the test runner to skip the error message checking when running corpus tests with Prism and updates the skipped tests in the BUILD file.
So now if a test is skipped, it's only because of the second reason. And we should minimize the number of tests that are skipped in that case.
> Skip error message checking when running Corpus tests with Prism

- parser/prism/Translator.cc
- parser/prism/Translator.h
- test/BUILD
- test/prism_regression/range.parse-tree.exp
- test/prism_regression/range.rb
Close #363 
Close #364
Close #368 
Close #369
`desguar/range` and `desguar/regex` revealed that we were missing some cases where we needed to do the dynamic constant assignment workaround. In the process of fixing this, Stan and I refactored the `translateConst` method to be a bit more straightforward.
> Fix desguar tests related to dynamic constant assignment

- parser/prism/Translator.cc
- test/prism_regression/def.parse-tree.exp
- test/prism_regression/def.rb
When the method has empty parenthesis, like `def foo(); end`, Sorbet's parser still generates an empty `Args` node instead of `NULL`.
Fixes #383 
> Generate empty Args node for method definitions with empty parentheses

- parser/prism/Translator.cc
- test/BUILD
- test/prism_regression/def_rest_params.parse-tree.exp
- test/prism_regression/def_rest_params.rb
Closes #381
Opens #393, having to do with the handling of `**nil` as a post param.
So uh... I think we (*I*) forgot that post params exist 😁 
> Fix failing local_vars test by translating post params

- parser/prism/Translator.cc
- test/prism_regression/until.parse-tree.exp
- test/prism_regression/until.rb
- test/prism_regression/while.parse-tree.exp
- test/prism_regression/while.rb
The current translation does not handle cases like:
```rb
begin
puts "foo"
end while false # or end until false
```
In such cases, Sorbet's parser creates `WhilePost` and `UntilPost` nodes instead.
Closes #385
> Handle post `while`/`until` modifiers

- parser/prism/Translator.cc
- test/BUILD
Closes #389 
We needed to slightly modify the locations of keyword arguments and params in order to match the behavior of Sorbet's legacy parser. This allows us to run four of the previously-failing namer tests.
> Modify locations of kw arguments and params to match legacy parser

- parser/prism/Translator.cc
- test/BUILD
- test/prism_regression/call.parse-tree.exp
- test/prism_regression/call.rb
Fixes #394
In cases like `foo.()`, the message would be `:call`, but the message location would have null start and end. In this case, we need to fall back to use the call operator location.
With #394 fixed, Prism is now passing all non-error-recovery LSP tests too. So in this PR I also add LSP tests into Prism Corpus tests.
> Correctly translate no-message calls' message locations

- parser/prism/Translator.cc
- test/BUILD
When the symbol is used as `a: 1`, the location should not include the colon.
Closes #388
Closes #378
Closes #377
Closes #374
Closes #371
Closes #367
I also found that after this PR, we can run and pass ALL non-error-related Sorbet tests 😄 
> Fix symbol location for hash, keyword argument keys

- main/options/options.h
- main/pipeline/pipeline.cc
- parser/prism/Parser.cc
- parser/prism/Parser.h
- parser/prism/Translator.cc
- parser/prism/Translator.h
- test/pipeline_test_runner.cc
This PR addresses a few smaller feedback from https://github.com/sorbet/sorbet/pull/8122 and https://github.com/sorbet/sorbet/pull/8485. I've linked to the respective comments in the commit messages, so I recommend reviewing by commits.
> Address small feedbacks

- main/pipeline/pipeline.cc
- parser/prism/Parser.cc
- parser/prism/Parser.h
- parser/prism/Translator.cc
- parser/prism/Translator.h
1. Makes it clear that it represents the program node, not nodes in general
2. Makes it easier to distinguish from Sorbet parser's Node class
Addressed https://github.com/sorbet/sorbet/pull/8485#discussion_r1943220198
> Rename `Prism::Node` to `Prism::ProgramNodeContainer`

- .github/workflows/ci.yml
As we start stacking it's going to be hard to keep CI to specific branches so instead we can run it on every branch and ignore the CI result when unnecessary.
> Run CI on every branch

- main/options/options.cc
- main/options/options.h
- main/pipeline/pipeline.cc
- prism_benchmarks/memory/run_benchmarks.sh
- prism_benchmarks/time/run_benchmarks.sh
- test/pipeline_test.bzl
- test/pipeline_test_runner.cc
- test/prism_location_test.sh
Fixes #415
Decided to rename `--parser sorbet` to `--parser original` because strictly speaking, [it's not Sorbet's parser](https://github.com/sorbet/sorbet/pull/8122#discussion_r1765457524). It's [typedruby](https://github.com/typedruby/typedruby), which is based on [whitequark](https://github.com/whitequark/parser). That's a mouthful, so "default" or "original" will do.
> Reame `--parser` option
