Shopify/sorbet

main/pipeline/pipeline.cc
test/prism_regression/if_else.parse-tree.exp
test/prism_regression/if_else.rb
test/prism_regression/if_elsif.parse-tree.exp
test/prism_regression/if_elsif.rb
test/prism_regression/if_empty_else.parse-tree.exp
test/prism_regression/if_empty_else.rb

Everything in here should be pretty standard! Also removed some old print statements.

Implement Prism -> Sorbet translation for `Else` node

---

parser/prism/Translator.cc
parser/prism/Translator.h
test/prism_regression/return.parse-tree.exp
test/prism_regression/return.rb
test/prism_regression/yield.parse-tree.exp
test/prism_regression/yield.rb

Implement Prism -> Sorbet translation for `return` and `yield`

---

parser/prism/Translator.cc
test/prism_regression/until.parse-tree.exp
test/prism_regression/until.rb

Implement Prism -> Sorbet translation for `until` loop blocks

---

parser/prism/Translator.cc
test/prism_regression/class.parse-tree.exp
test/prism_regression/class.rb
test/prism_regression/module.parse-tree.exp
test/prism_regression/module.rb

Implement Prism -> Sorbet translation for `module` declarations

---

parser/prism/Parser.cc
parser/prism/Parser.h
parser/prism/Translator.cc
test/prism_regression/regexp.parse-tree.exp
test/prism_regression/regexp.rb

Implement translation for `Regexp` node

---

parser/prism/Translator.cc
test/prism_regression/next.parse-tree.exp
test/prism_regression/next.rb

Implement translation for `next` node

---

parser/prism/Translator.cc

Most cases already had these comments, but not all. This PR just fills in the rest.
This should be helpful for new readers tryhing to make sense of these, without needing to constant jump into the docs

Add comments to all node `case` statements

---

parser/prism/Translator.cc
test/prism_regression/case_match.parse-tree.exp
test/prism_regression/case_match.rb

Implements basic Hash patterns.
Builds on top of #251
Closes #101
Part of #142

Implement Prism -> Sorbet translation for basic Hash patterns

---

.vscode/tasks.json
parser/prism/Translator.cc
test/prism_regression/defined.parse-tree.exp
test/prism_regression/defined.rb

Closes https://github.com/Shopify/sorbet/issues/82
A new test case for the translation has been added.

Implement translation for `PM_DEFINED_NODE`

---

parser/prism/Translator.cc
test/prism_regression/alias.parse-tree.exp
test/prism_regression/alias.rb

Implement Prism -> Sorbet translation for the `alias` keyword

---

parser/prism/Translator.cc
test/prism_regression/assign_to_class_variable.parse-tree.exp
test/prism_regression/assign_to_class_variable.rb
test/prism_regression/assign_to_global_variable.parse-tree.exp
test/prism_regression/assign_to_global_variable.rb
test/prism_regression/assign_to_index.parse-tree.exp
test/prism_regression/assign_to_index.rb
test/prism_regression/assign_to_instance_variable.parse-tree.exp
test/prism_regression/assign_to_instance_variable.rb
test/prism_regression/assign_to_local_variable.parse-tree.exp
test/prism_regression/assign_to_local_variable.rb
test/prism_regression/assign_to_method_result.parse-tree.exp
test/prism_regression/assign_to_method_result.rb

Closes #58 
Closes #67
Closes #98
Closes #110
Closes #115

Implement Prism -> Sorbet translation for more target types

---

parser/prism/Translator.cc
test/prism_regression/rescue.parse-tree.exp
test/prism_regression/rescue.rb

Closes https://github.com/Shopify/sorbet/issues/159
New test cases were added

Translate rescue modifier nodes

---

.github/workflows/ci.yml
tools/scripts/verify_prism_regression_tests.sh

Add a new script to verify that our prism regression parse trees are up to date, and run that script in CI to make sure that we are updating our parsing output as Sorbet master changes.
See CI output!

Verify test expectations in CI

---

parser/prism/Translator.cc
test/prism_regression/shareable_constant.parse-tree.exp
test/prism_regression/shareable_constant.rb

Implement Prism -> Sorbet translation for shareable constants

---

parser/prism/Translator.cc
parser/prism/Translator.h
test/prism_regression/literal_regexp.parse-tree.exp
test/prism_regression/literal_regexp.rb
test/prism_regression/literal_symbol.parse-tree.exp
test/prism_regression/literal_symbol.rb

Implement Prism -> Sorbet translation for interpolated Symbol and Regexp literals

---

parser/prism/Translator.cc
test/prism_regression/ensure.parse-tree.exp
test/prism_regression/ensure.rb
test/prism_regression/rescue.parse-tree.exp
test/prism_regression/rescue.rb

Translate `ensure` clause

---

test/BUILD

We can add the list in #370 to `test/BUILD` and start running rewriter tests too.

Update test/BUILD for rewriter tests

---

main/pipeline/pipeline.cc
main/pipeline/pipeline.h
parser/prism/Parser.cc
parser/prism/Parser.h
test/pipeline_test_runner.cc

Hide `runPrismParser` from `pipeline.h`

---

parser/prism/Translator.cc
parser/prism/Translator.h

Default `inlineIfSingle` to `true`

---

parser/prism/Parser.cc
parser/prism/Parser.h
parser/prism/Translator.h

Inline `ParserStorage`

---

test/helpers/position_assertions.cc
test/helpers/position_assertions.h
test/pipeline_test_runner.cc

Fix parser compilation error

---

.github/workflows/ci.yml

We'd like to merge this workflow to Sorbet as it's needed for Prism migration and having it committed would make things easier. But we don't have to execute it unless we're on our fork.

Run Github Action workflow only on Shopify's fork

---

test/BUILD
test/pipeline_test_runner.cc

Merging master into the feature branch is a gnarly process. We missed a few things that this PR is adding back.
1. RBS rewriters weren't being triggered
2. Removed outdated CI configuration unrelated to prism

Fix incorrect edits during merging master
